const data = [
   {
      id: getUUID(),
      title: 'Joker',
      description:
         'In 1981 Gotham City, a struggling, mentally ill comic battles to be seen. His life takes a dark, gut-wrenching turn after he lashes back at attackers.',
      genre: 'Violence',
      genres: 'US Movies, Social Issue Dramas, Crime Movies',
      duration: '2h 1m',
      age: '18',
      img: 'joker',
   },
   {
      id: getUUID(),
      title: 'John 3 Wick',
      description:
         'With a $14 million bounty on his head, elite hitman John Wick must battle every killer in his path to reach old allies and redeem his life.',
      cast: 'Halle Berry, Keanu Reeves, more',
      genre: 'Violence',
      genres: 'US Movies, Action & Adventure, Crime Movies',
      duration: '2h 10m',
      age: '18',
      img: 'john-3-wick',
   },
   {
      id: getUUID(),
      title: 'Red Notice',
      description:
         'An FBI profiler pursuing the world most wanted art thief becomes his reluctant partner in crime to catch an elusive crook who always one step ahead.',
      cast: 'Dwayne Johnson, Ryan Reynolds, more',
      genre: 'Violence',
      genres: 'US Movies, Action & Adventure, Crime Movies',
      duration: '1h 57m',
      age: '13',
      img: 'red-notice',
   },
   {
      id: getUUID(),
      title: 'Red Notice',
      description:
         'An FBI profiler pursuing the world most wanted art thief becomes his reluctant partner in crime to catch an elusive crook who always one step ahead.',
      cast: 'Dwayne Johnson, Ryan Reynolds, more',
      genre: 'Violence',
      genres: 'US Movies, Action & Adventure, Crime Movies',
      duration: '1h 57m',
      age: '13',
      img: 'red-notice',
   },
   {
      id: getUUID(),
      title: 'Silverton Siege',
      description:
         'After a failed sabotage mission, a trio of anti-apartheid freedom fighters ends up in a tense bank hostage situation. Based on a true story.',
      cast: 'Thabo Rametsi, Arnold Vosloo, more',
      genre: 'Violence',
      genres: 'South African, Social Issue Dramas ',
      duration: '1h 41m',
      age: '16',
      img: 'silverton-siege',
   },
   {
      id: getUUID(),
      title: 'The Takedown',
      description:
         'Forced to reteam after a decade, two mismatched cops investigate a murder in a divided French town, where a wider conspiracy looms.',
      cast: 'Omar Sy, Laurent Lafitte, more',
      genre: 'Violence',
      genres: 'Action & Adventure, Crime Movies, French',
      duration: '2h 1m',
      age: '18',
      img: 'the-takedown',
   },
   {
      id: getUUID(),
      title: 'Sunderground',
      description:
         'After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission to take down a brutal dictator.',
      cast: 'Ryan Reynolds, Mélanie Laurent, more',
      genre: 'Violence',
      genres: 'Action & Adventure, Crime Movies',
      duration: '2h 8m',
      age: '18',
      img: 'sunderground',
   },
   {
      id: getUUID(),
      title: 'Triple Frontier',
      description:
         'Loyalties are tested when five former special forces operatives reunite to steal a drug lord fortune, unleashing a chain of unintended consequences.',
      cast: 'Ben Affleck, Oscar Isaac, Charlie Hunnam, more',
      genre: 'Violence',
      genres: 'Action & Adventure, US Movies',
      duration: '2h 5m',
      age: '18',
      img: 'triple-frontier',
   },
   {
      id: getUUID(),
      title: 'white house down',
      description:
         'When a paramilitary group engineers a violent takeover of the White House, the president must try to hide from the attackers until he can be rescued.',
      cast: 'Channing Tatum, Jamie Foxx, more',
      genre: 'Violence',
      genres: 'Action & Adventure, Crime Movies',
      duration: '2h 11m',
      age: '16',
      img: 'white-house-down',
   },
   {
      id: getUUID(),
      title: 'Extraction',
      description:
         'A hardened mercenary mission becomes a soul-searching race to survive when he sent into Bangladesh to rescue a drug lord kidnapped son.',
      cast: 'Chris Hemsworth, Rudhraksh Jaiswal, more',
      genre: 'Violence',
      genres: 'US Movies, Movies Based on Books, Action & Adventure',
      duration: '1h 57m',
      age: '18',
      img: 'extraction',
   },
];
